spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.9:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      validation-query: select 1
      filters: stat,wall,slf4j,config